### ISSUE TITLE
director role: Do not create stackrc file before the undercloud install

### ISSUE THREAD

**Issue by shwetha-h-p** [oasis-roles/ansible_collection_osp#5]
Creating the stackrc file is leading to failure in the undercloud install. What i found was, since the stackrc file already exists, the undercloud install command execution assumes the installation has previously taken place and searches for the undercloud-passwords.conf, file.

https://github.com/oasis-roles/ansible_collection_osp/blob/master/roles/director/tasks/main.yml . Line number 38 - 46

=======================
Log message:
=======================

[stack@director-osp13 ~]$ cat .instack/install-undercloud.log 
2020-06-02 02:22:18,313 INFO: Logging to /home/stack/.instack/install-undercloud.log
2020-06-02 02:22:18,483 INFO: Checking for a FQDN hostname...
2020-06-02 02:22:18,524 INFO: Static hostname detected as director-osp13.test.c0.psi.rdu2.redhat.com
2020-06-02 02:22:18,564 INFO: Transient hostname detected as director-osp13.test.c0.psi.rdu2.redhat.com
2020-06-02 02:22:18,568 DEBUG: An exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/instack_undercloud/undercloud.py", line 2438, in install
    _validate_configuration()
  File "/usr/lib/python2.7/site-packages/instack_undercloud/undercloud.py", line 882, in _validate_configuration
    _validate_passwords_file()
  File "/usr/lib/python2.7/site-packages/instack_undercloud/undercloud.py", line 862, in _validate_passwords_file
    raise validator.FailedValidation(message)
FailedValidation: The /home/stack/undercloud-passwords.conf file is missing.  This will cause all service passwords to change and break the existing undercloud. 
2020-06-02 02:22:18,570 ERROR: 
#############################################################################
Undercloud install failed.

Reason: The /home/stack/undercloud-passwords.conf file is missing.  This will cause all service passwords to change and break the existing undercloud. 

See the previous output for details about what went wrong.  The full install
log can be found at /home/stack/.instack/install-undercloud.log.

#############################################################################

When i deleted the stackrc file and re-ran the install, it worked.

**Comment by greg-hellings** [comment]
This is done. Coming in PR.
